### ISSUE TITLE
[FORGE] Incompatible with GroovyModLoader

### ISSUE THREAD

**Issue by null2264** [Erdragh/AstralBot#4]
Caused by GML's jackson JiJ, it works fine when I exclude jackson from JDA shade on my personal build.

Log with minimal reproduction setup (with only AstralBot and GML installed):

```
[17:32:40] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.2.19, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[17:32:40] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.9 by Eclipse Adoptium; OS Linux arch amd64 version 6.6.7-x64v2-xanmod1-1
[17:32:40] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver
[17:32:40] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/ziro/Downloads/mctest/forge/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2365!/ Service=ModLauncher Env=SERVER
[17:32:41] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/ziro/Downloads/mctest/forge/libraries/net/minecraftforge/fmlcore/1.20.1-47.2.19/fmlcore-1.20.1-47.2.19.jar is missing mods.toml file
[17:32:41] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/ziro/Downloads/mctest/forge/libraries/net/minecraftforge/javafmllanguage/1.20.1-47.2.19/javafmllanguage-1.20.1-47.2.19.jar is missing mods.toml file
[17:32:41] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/ziro/Downloads/mctest/forge/libraries/net/minecraftforge/lowcodelanguage/1.20.1-47.2.19/lowcodelanguage-1.20.1-47.2.19.jar is missing mods.toml file
[17:32:41] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/ziro/Downloads/mctest/forge/libraries/net/minecraftforge/mclanguage/1.20.1-47.2.19/mclanguage-1.20.1-47.2.19.jar is missing mods.toml file
[17:32:42] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 26 dependencies adding them to mods collection
[17:32:43] [main/INFO] [or.gr.gm.ma.MappingsProvider/]: Starting runtime mappings setup...
[17:32:43] [main/INFO] [or.gr.gm.in.lo.ModLocatorInjector/]: Injecting ScriptModLocator candidates...
[17:32:43] [main/INFO] [or.gr.gm.sc.ScriptModLocator/]: Injected Jimfs file system
[17:32:43] [main/INFO] [or.gr.gm.sc.ScriptModLocator/]: Skipped loading script mods from directory /home/ziro/Downloads/mctest/forge/mods/scripts as it did not exist.
[17:32:43] [main/INFO] [or.gr.gm.in.lo.ModLocatorInjector/]: Injected ScriptModLocator mod candidates. Found 0 valid mod candidates and 0 broken mod files.
Exception in thread "main" java.lang.module.ResolutionException: Modules org.groovymc.gml.groovyjij.com.fasterxml.jackson.core.jackson.annotations and astralbot export package com.fasterxml.jackson.annotation to module commongroovylibrary
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
[17:32:47] [GML Mappings Thread/INFO] [or.gr.gm.ma.MappingsProvider/]: Found version metadata from piston-meta.
[17:32:47] [GML Mappings Thread/ERROR] [or.gr.gm.ma.MappingsProvider/]: Caught exception while setting up mappings...
java.lang.NoClassDefFoundError: org/apache/commons/codec/binary/Hex
	at org.groovymc.gml.mappings.MappingsProvider.checkAndUpdateVersionFile(MappingsProvider.groovy:192) ~[?:?] {}
	at org.groovymc.gml.mappings.MappingsProvider.access$1(MappingsProvider.groovy) ~[?:?] {}
	at org.groovymc.gml.mappings.MappingsProvider$_startMappingsSetup_closure3.doCall(MappingsProvider.groovy:107) ~[?:?] {}
	at org.groovymc.gml.mappings.MappingsProvider$_startMappingsSetup_closure3.call(MappingsProvider.groovy) ~[?:?] {}
	at groovy.lang.Closure.run(Closure.java:505) ~[?:?] {}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {}
Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.binary.Hex
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	... 6 more
```

**Comment by null2264** [comment]
Fixed on v1.0.2
